tipo = {
    0: "JSNS",
    1: "Integral",
    2: "",
    3: "Float",
    4: "",
    5: "String",
    6: "",
    7: "Variable",
    8: "Coma",
    9: "",
    10: "Igual a",
    11: "Dos punto",
    12: "Punto y coma",
    13: "Menos que",
    14: "Menos o igual que",
    15: "Más que",
    16: "Más o igual que",
    17: "No",
    18: "No igual que",
    19: "",
    20: "Igual que",
    21: "Suma",
    22: "Sumar a",
    23: "Resta",
    24: "Restar a",
    25: "Multiplicacion",
    26: "Multiplicar a",
    27: "División",
    28: "Dividir a",
    29: "",
    30: "",
    31: "Comentario",
    32: "",
    33: "OR",
    34: "",
    35: "AND",
    36: "Parentesis inicio",
    37: "Parentesis final",
    38: "Llave inicio",
    39: "Llave final",
    40: "Corchete inicio",
    41: "Corchete final",
    42: "",
    43: "Palabra reservada",
    44: ""
}

palabras_reservadas = {

}