tipo = {
    0: "JSNS",
    1: "integer",
    2: "",
    3: "Float",
    4: "",
    5: "string",
    6: "Fin",
    7: "identifier",
    8: "Coma",
    9: "",
    10: "Igual a",
    11: "Dos punto",
    12: "punto y coma",
    13: "Menos que",
    14: "Menos o igual que",
    15: "Más que",
    16: "Más o igual que",
    17: "init/end",
    18: "No igual que",
    19: "",
    20: "Igual que",
    21: "Suma",
    22: "Sumar a",
    23: "Resta",
    24: "Restar a",
    25: "Multiplicacion",
    26: "Multiplicar a",
    27: "División",
    28: "Dividir a",
    29: "",
    30: "",
    31: "Comentario",
    32: "",
    33: "OR",
    34: "",
    35: "AND",
    36: "Parentesis inicio",
    37: "Parentesis final",
    38: "llave inicio",
    39: "llave final",
    40: "Corchete inicio",
    41: "Corchete final",
    42: "",
    43: "Palabra reservada",
    44: ""
}

errores = {
    0: "error inicial",
    1: "error Integral",
    2: "error Integral",
    3: "error Float",
    4: "error String",
    5: "error String",
    6: "error Variable",
    7: "error Variable",
    8: "error Coma",
    9: "error igual",
    10: "error Igual a",
    11: "error Dos punto",
    12: "error Punto y coma",
    13: "error Menos que",
    14: "error Menos o igual que",
    15: "error Más que",
    16: "error Más o igual que",
    17: "error No",
    18: "error No igual que",
    19: "error Igual que",
    20: "error Igual que",
    21: "error Suma",
    22: "error Sumar a",
    23: "error Resta",
    24: "error Restar a",
    25: "error Multiplicacion",
    26: "error Multiplicar a",
    27: "error División",
    28: "errorDividir a",
    29: "error Comentario",
    30: "error Comentario",
    31: "error Comentario",
    32: "error OR",
    33: "error OR",
    34: "error AND",
    35: "error AND",
    36: "error Parentesis inicio",
    37: "error Parentesis final",
    38: "error Llave inicio",
    39: "error Llave final",
    40: "error Corchete inicio",
    41: "error Corchete final",
    42: "error palabra reservada",
    43: "error Palabra reservada",
    44: "error espacio"
}

palabras_reservadas = {

}